### ISSUE TITLE
Get proper recording of Drone Control and video signal

### ISSUE THREAD

**Issue by danpelis** [TimDemetriades/DDS#3]
We should develop a gnu-radio or even just pure Python program in order to do some general signal analysis. The RSA was great but we should be focusing on how well the Pluto can receive these signals from the Drone

**Comment by cdepalma141** [comment]
We should develop a gnu-radio or even just pure Python program in order to do some general signal analysis. The RSA was great but we should be focusing on how well the Pluto can receive these signals from the Drone
